INSTALL(TARGETS openpose-plus ARCHIVE DESTINATION lib)
INSTALL(DIRECTORY include DESTINATION .)

INCLUDE(CPack)
# SET(CPACK_PACKAGE_DIRECTORY ${CMAKE_SOURCE_DIR}/release)
SET(CPACK_GENERATOR "TGZ")
SET(CPACK_PACKAGE_VERSION "latest")
